# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1954c6e1fc5b56af78315f665da347e991b8f145498b22c9a17e93e5ee6099df43ffcaad9bbe527ad630fd415809b8a487b3108341aacdeb632f43cb60594394

test:
  secret_key_base: 7e4c5ca35280f217c087f5249b5bd00c45fd8f08624081336dc4d4a933d99c9b51b279247f75c7c4be1a1ac354cc13dc3d80be00ae5623a52189ddf161f8d137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
